[package]
name = "vox-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
fs2.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
vox-domain = { path = "../vox-domain" }
vox-connections = { path = "../vox-connections" }

[dev-dependencies]
prost-types.workspace = true
tonic.workspace = true
vox-tinvest = { path = "../vox-tinvest" }

[lints]
workspace = true
